"""Export an edited animal .blend straight back into the app:

    blender -b blends/cat.blend -P blender/export_blend.py -- --out critter_cat.glb

Selects every object in the "Critters" collection (the reference ground,
camera and lights are ignored), writes models/<out> and mirrors it into
web/models/.
"""
import bpy
import sys
import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
if "--out" not in argv:
    raise SystemExit("usage: blender -b blends/<animal>.blend -P blender/export_blend.py -- --out critter_<animal>.glb")
out = argv[argv.index("--out") + 1]

col = bpy.data.collections.get("Critters")
objs = list(col.objects) if col else []
if not objs:
    raise SystemExit("no objects in the Critters collection — was this file generated by make_blend.py?")

sel = set(objs)
for o in bpy.data.objects:
    o.select_set(o in sel)
bpy.context.view_layer.objects.active = objs[0]

path = os.path.join(ROOT, "models", out)
bpy.ops.export_scene.gltf(
    filepath=path,
    export_format='GLB',
    use_selection=True,
    export_cameras=False,
    export_lights=False,
    export_apply=True,
)
web = os.path.join(ROOT, "web", "models")
os.makedirs(web, exist_ok=True)
shutil.copy2(path, os.path.join(web, out))
print(f"[export] {out}: {len(objs)} objects -> models/ + web/models/")
